#!/bin/bash
# 1.2.0 - 2021-09-14
# - Add -p switch to pull answer from clipboard when adding a question
# - Improve option parsing
# - Allow -e when adding answer to open new question file in editor
# - Allow multi-line input when adding interactively
# - Allow '#atag' to translate to 'tag:atag' in spotlight search
# - Allow configuration via environment variables
#
# 1.1.1
# - Only opens url/copies code from one note if there are multiple answers
#
# Usage:
# Ask a question using natural language
# $ qq [search terms]
#
# Search using @tags
# $ qq awk replace @unix
#
# Search including macOS tags
# $ qq '#awk #unix' replace
#
# Add a new question answer pair
# $ qq -a "This is the question" "This is the answer"
#
# Add a new question using clipboard as answer
# $ qq -p "This is the question"
#
# If no arguments are provided with -a or -p, input will be
# requested interactively.
#
# To edit an existing answer or use the editor to answer a
# new question, add the `-e` flag. If used alone, the first
# matching answer will be opened in your editor.
#
# Configuration is done via environment variables:
#
#  QQ_NOTES_DIR - Path to Markdown files
#  QQ_NOTES_EXT - Extension of markdown files (default md)
#  QQ_NOTES_PRE - Prefix of question files (default ??)
#  QQ_EDITOR    - Text editor to use (default $EDITOR)
#
#  Example:
#  export QQ_NOTES_DIR="/Users/ttscoff/Dropbox/Notes"
#  export QQ_NOTES_EXT="markdown"

: ${QQ_NOTES_DIR:="$HOME/Dropbox/Notes/nvALT2.2"}
: ${QQ_NOTES_EXT:="md"}
: ${QQ_NOTES_PRE:="??"}
: ${QQ_EDITOR:=$EDITOR}

__qq () {
  ### CONFIG
  # notes folder, for note creation and limiting searches
  local NOTESDIR=$QQ_NOTES_DIR
  # extension used for your notes
  local NOTESEXT=$QQ_NOTES_EXT
  # the prefix you use to separate "Question" notes
  local NOTESPRE=$QQ_NOTES_PRE
  # editor command to use for modifying answers
  local QQEDITOR=$QQ_EDITOR

  NOTESDIR="${NOTESDIR%/}/"

  # Exlude file names containing these phrases, separated by colons
  local EXCLUDENAMES="what was I doing"

  #### END CONFIG
  local INPUT QQQUERY HAS_OPENED_URL HAS_COPIED_TEXT NOTESPREESC QUESTION ANSWER appname url
  local EXCLUDEQQQUERY=$(__qq_query_exclude_all "$EXCLUDENAMES")

  local EDITING=false
  local ADDING=false
  local PASTING=false

  OPTIND=1

  while getopts "peah?" opt; do
    case $opt in
      p)
        ADDING=true
        PASTING=true
        ;;
      e)
        EDITING=true
        ;;
      a)
        ADDING=true
        ;;
      h|\?)
        __qq_help
        exit 0
        ;;
    esac
  done

  shift $((OPTIND-1))
  [ "${1:-}" = "--" ] && shift

  HAS_COPIED_TEXT=false
  HAS_OPENED_URL=false

  if [[ "$ADDING" == "true" || $# == 0 ]]; then
    if [ $# == 2 ]; then
      QUESTION=$1
      ANSWER=$2
    elif [ $# -le 1 ]; then
      if [ $# == 1 ]; then
        QUESTION=$1
        echo "Question: $QUESTION"
      else
        echo -n "Question: "
        read QUESTION
      fi

      if $PASTING; then
        ANSWER=$(pbpaste)
      elif [[ "$EDITING" == "false" ]]; then
        echo "Answer (Ctrl-D to end):"
        ANSWER=$(cat)
      fi
    else
      echo "Invalid number of arguments for -a(dd). Requires question and answer (or no arguments to input them at runtime)."
      echo "example: ${0##*/} -a \"What is the meaning of life?\" \"42\""
      exit 1
    fi
    local QQFILE="${NOTESDIR}$NOTESPRE $QUESTION.$NOTESEXT"

    if $EDITING; then
      echo -n "$ANSWER" >> "$QQFILE"
      $QQEDITOR "$QQFILE"
    else
      echo -n "$ANSWER" >> "$QQFILE" && echo "Question added and answered." || echo "Something went wrong"
    fi
  else
    # local INPUT=$@
    # QQQUERY="'kind:text AND filename:.$NOTESEXT AND filename:$NOTESPRE$(__qq_query_include_all "${*%\?}")${EXCLUDEQQQUERY}'"
    QQQUERY="mdfind -onlyin '$NOTESDIR' -interpret '(kind:text OR kind:markdown) AND filename:$NOTESEXT AND filename:$NOTESPRE $(__qq_query_include_all "${*%\?}")${EXCLUDEQQQUERY}'"
    RESULTS=$(eval $QQQUERY)

    if [[ "$RESULTS" == "" ]]; then
      QQQUERY="mdfind -onlyin '$NOTESDIR' -interpret '(kind:text OR kind:markdown) AND filename:$NOTESEXT AND filename:$NOTESPRE $(__qq_query_include_all OR "${*%\?}")${EXCLUDEQQQUERY}'"
      RESULTS=$(eval $QQQUERY)
    fi

    if [[ "$RESULTS" == "" ]]; then
      echo "Sorry, I don't know the answer to that question."
      exit 2
    else
      if $EDITING; then
        ANSWER=$(echo "$RESULTS"|head -n 1)
        $QQEDITOR "$ANSWER"
      else
        echo -e "$RESULTS" | while read LINE; do
          if [[ "$LINE" =~ ^$ ]]; then
            echo "Sorry, I don't know the answer to that question."
            exit 1;
          fi
          QUESTION=`basename "$LINE" ".$NOTESEXT"`
          echo -n "Q: "
          NOTESPREESC=`echo "$NOTESPRE"|sed -E 's/([\?\!\$\`\"]) ?/\\\\\1/g'`
          echo "$QUESTION"|sed -E "s/$NOTESPREESC ?//g"|sed -E 's/([^\?])$/\1?/'
          echo -n "A: "
          cat "$LINE"|sed -E 's/@\([^\)]+\) ?//g'|sed -E 's/@copy\(([^\)]+)\)/\1/'|sed -E 's/@open\(([^\)+]*)\)/Related URL: \1/'|sed -E 's/@[^\( ]+ ?//g'|sed -E 's/^[   ]*|[  ]*$//g'
          if [[ `cat "$LINE"|grep -E '@copy\('` && $HAS_COPIED_TEXT == false ]]; then
            cat "$LINE"|grep '@copy('|sed -E 's/.*@copy\(([^\)]+)\).*/\1/'|tr -d '\n'|pbcopy
            echo "Example in clipboard"
            HAS_COPIED_TEXT=true
          fi

          if [[ `cat "$LINE"|grep -E '@open\('` && $HAS_OPENED_URL == false ]]; then
            url=$(cat "$LINE"|grep '@open('|sed -E 's/.*@open\(([^\)]+)\).*/\1 /'|tr -d '\n')
            open -g $url
            echo "Opened URL"
            HAS_OPENED_URL=true
          fi
        done
      fi
    fi
  fi
  exit 0
}

__qq_esc () {
  echo "$*"|sed 's/"/\\\"/g'|sed 's/#/tag:/g'
}

__qq_remove_stopwords () {
  local input=$1
  declare -a STOPWORDS=( what which is can how do my where when why that the was who this I )
  for word in ${STOPWORDS[@]}; do
    input=$(echo "$input"|sed -E "s/(^| )$word([\.\,\? ]|$)/\1/g")
  done
  echo -n "$input"
}

__qq_query_include_all () {
  local bool="AND"
  if [[ $1 == "OR" ]]; then
    bool="OR"
    shift
  fi
  if [[ "$*" != "" ]]; then
    local input=$(__qq_remove_stopwords "$*")

    declare -a query_array=( "$@" )
    local query=" AND ("
    for i in ${query_array[@]}; do
        query="${query}`__qq_esc $i` $bool "
    done
    echo -n "$query"|sed -e 's/ AND $/)/' -e 's/ OR $/)/'
  fi
}

__qq_query_exclude_all () {
  local input="$1"
  local OLDIFS=$IFS
  IFS=":"
  set $input
  declare -a query_array=( "$@" )
  local query=' NOT ('
  for i in ${query_array[@]}; do
      query="${query}filename:\"`__qq_esc $i`\" OR "
  done
  echo -n "$query"|sed 's/ OR $/)/'
  IFS=$OLDIFS
}

__qq_help () {
  appname=`basename $0`
  echo "$appname: build a knowledgebase with plain text files"
  echo "Find an answer: $appname \"terms to search for\""
  echo "Add a question/answer: $appname -a \"Question in natural language\" \"Succinct answer\""
  echo "Add a question/answer interactively: $appname -a"
  echo "Add a question with answer from clipboard: $appname -p [\"Optional Question\"]"
  echo "Edit an answer: $appname -e \"terms to search for\" # first question found is edited"

  echo
  echo "Configuration:"
  echo "QQ_NOTES_DIR: ${QQ_NOTES_DIR}"
  echo "QQ_NOTES_EXT: ${QQ_NOTES_EXT}"
  echo "QQ_NOTES_PRE: ${QQ_NOTES_PRE}"
  echo "QQ_EDITOR: ${QQ_EDITOR}"
}

# __qq_query_include_all OR $@
__qq "$@"
